version: "3.8"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ssw0rdAndSomeText"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/mssql
      